services:
  mariadb:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE: postal
      MARIADB_ROOT_PASSWORD: postal
    volumes:
      - ./mariadb-data:/var/lib/mariadb


volumes:
  mariadb-data:

